### ISSUE TITLE
Add Ammo Shop

### ISSUE THREAD

**Issue by x0Z3ro0xsGirl** [x0Z3ro0x/FiveM-Server-PUBLIC#2]
Add ammo shop inside of Amunation

**Comment by x0Z3ro0x** [comment]
We already have menus in game that I've added. Those are just basic HTML and CSS. We should be able to add basic buttons and javascript functionality to turn an HTML menu into something with buttons and actions. Once you do that, well you have a "shop".

I'll get started on this now 😃

**Comment by x0Z3ro0x** [comment]
Took longer than I expected. Browsers are taken for granted! Anyway I think the menu system I created can be improved upon. I'll leave that up to you since it's your idea. Maybe pictures or a slider for multiple items? Enjoy the new ammo shop!
